=== yutian1012/migrate-core/src/main/resources/xml/tables.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xsd:element name="tables">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="table" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="table">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="fields" minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- field标签可以出现多次，至少出现1次 -->
							<xsd:element ref="field" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="where">
					<xsd:complexType>
						<xsd:sequence>
							<!-- field标签可以出现多次，至少出现1次 -->
							<xsd:element ref="condition" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="formats">
					<xsd:complexType>
						<xsd:sequence>
							<!-- format标签可以出现多次，至少出现1次 -->
							<xsd:element ref="format" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="constraints" minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- constraint标签可以出现多次，至少出现1次 -->
							<xsd:element ref="constraint" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="splits">
					<xsd:complexType>
						<xsd:sequence>
							<!-- format标签可以出现多次，至少出现1次 -->
							<xsd:element ref="split" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="skip">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="true"/>
						<xsd:enumeration value="false"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
					    <xsd:enumeration value="MIGRATE"/>
					    <xsd:enumeration value="UPDATE"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="to" use="required"></xsd:attribute>
			<xsd:attribute name="from" use="required"></xsd:attribute>
			<xsd:attribute name="note" use="required"></xsd:attribute>
			<xsd:attribute name="main"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="field">
		<xsd:complexType>
			<xsd:attribute name="type">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="VARCHAR"></xsd:enumeration>
						<xsd:enumeration value="DATE"></xsd:enumeration>
						<xsd:enumeration value="NUMERIC"></xsd:enumeration>
						<xsd:enumeration value="BLOB"></xsd:enumeration>
						<xsd:enumeration value="TEXT"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="name" use="required"></xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
			<xsd:attribute name="valueType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="FIXED"></xsd:enumeration>
						<xsd:enumeration value="FIELD"></xsd:enumeration>
						<xsd:enumeration value="GENCODE"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="note"></xsd:attribute>
			<xsd:attribute name="value"></xsd:attribute>
			<xsd:attribute name="forLog">
				<xsd:simpleType>
					<xsd:restriction base="xsd:boolean"></xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="format">
		<xsd:complexType>
			<xsd:attribute name="clazz"></xsd:attribute>
			<!-- <xsd:attribute name="formatParameter"></xsd:attribute> -->
			<xsd:attribute name="fieldName"></xsd:attribute>
			<xsd:attribute name="defaultValue"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="condition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="field" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="LE"></xsd:enumeration>
						<xsd:enumeration value="LT"></xsd:enumeration>
						<xsd:enumeration value="GE"></xsd:enumeration>
						<xsd:enumeration value="GT"></xsd:enumeration>
						<xsd:enumeration value="ISNOTNULL"></xsd:enumeration>
						<xsd:enumeration value="ISNULL"></xsd:enumeration>
						<xsd:enumeration value="LIKE"></xsd:enumeration>
						<xsd:enumeration value="LLIKE"></xsd:enumeration>
						<xsd:enumeration value="RLIKE"></xsd:enumeration>
						<xsd:enumeration value="IN"></xsd:enumeration>
						<xsd:enumeration value="NOTIN"></xsd:enumeration>
						<xsd:enumeration value="EQUAL"></xsd:enumeration>
						<xsd:enumeration value="NEQUAL"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="constraint">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="field" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="PRIMARY"></xsd:enumeration>
						<xsd:enumeration value="FOREIGNKEY"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
			<xsd:attribute name="value"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="split">
		<xsd:complexType>
			<xsd:attribute name="clazz"></xsd:attribute>
			<xsd:attribute name="fieldName"></xsd:attribute>
			<xsd:attribute name="defaultValue"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:attribute name="applyType">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="TARGET"></xsd:enumeration>
				<xsd:enumeration value="SOURCE"></xsd:enumeration>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
</xsd:schema>

=== yutian1012/migrate-core/src/main/resources/xml/patentPctApplySupply.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="wf_patent_support_foreign" from="patent_upload_model" note="专利PCT申请补录数据迁移" skip="false">
    	<fields>
    		<field name="id" applyType="TARGET" valueType="FIELD" value="id" note="主键字段"></field>
    		<field name="id" applyType="SOURCE"/>
    		<field name="patentName" applyType="TARGET" valueType="FIELD" value="patentName"/>
    		<field name="patentName" applyType="SOURCE"/>
    		<field name="applyNo" applyType="TARGET" valueType="FIELD" value="patentNo"/>
    		<field name="patentNo" applyType="SOURCE" note="申请号" forLog="true"></field>
    		<field name="applyDate" applyType="TARGET" valueType="FIELD" value="requestDate"/>
    		<field name="requestDate" applyType="SOURCE"/>
    		<field name="authDate" applyType="TARGET" valueType="FIELD" value="pctDate"/>
    		<field name="pctDate" applyType="SOURCE"/>
    		<field name="country" applyType="TARGET" valueType="FIELD" value="requestCountry"/>
    		<field name="requestCountry" applyType="SOURCE"/>
    		<field name="applyer" applyType="TARGET" valueType="FIELD" value="firstRequest"/>
    		<field name="firstRequest" applyType="SOURCE"/>
    		<field name="money" applyType="TARGET" valueType="FIELD" value="transfermoney"/>
    		<field name="transfermoney" applyType="SOURCE"/>
    		<field name="statusType" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="type" applyType="TARGET" valueType="FIXED" value="0"/>
    	</fields>
    	<where>
    		<condition type="EQUAL" applyType="SOURCE">
    			<field name="costtype" applyType="SOURCE" valueType="FIXED" value="SQ5"></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.PctNoFormater" fieldName="patentNo"/>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="requestCountry">{'QT':'CN','MG':'US','ZG':'CN','RB':'JP','OM':'EP'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/zpatenthistory_batch.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="UPDATE" to="z_patent_history" from="tbatch" note="旧系统专利批次信息更新" skip="false">
    	<fields>
    		<field name="batch" applyType="TARGET" valueType="FIELD" value="name" note="批次信息"></field>
    		<field name="name" applyType="SOURCE" note="批次名"></field>
    		<field name="code" applyType="SOURCE"/>
    	</fields>
    	<where>
            <condition type="ISNOTNULL" applyType="TARGET">
                <field name="batch" applyType="TARGET"></field>
            </condition>
    		<condition type="EQUAL" applyType="TARGET">
    			<field name="batch" applyType="TARGET" valueType="FIELD" value="code" ></field>
    		</condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/zpatenthistory.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利旧系统数据处理 -->
   <table type="MIGRATE" to="z_patent_history" from="tpatentallo" note="专利旧系统数据迁移" skip="false">
    	<fields>
    		<field name="id" applyType="TARGET" valueType="FIELD" value="id" note="主键字段"></field>
    		<field name="id" applyType="SOURCE"/>
    		<field name="patentName" applyType="TARGET" valueType="FIELD" value="patentName"/>
    		<field name="patentName" applyType="SOURCE"/>
    		<field name="appNumber" applyType="TARGET" valueType="FIELD" value="patentNo"/>
    		<field name="patentNo" applyType="SOURCE" note="申请号" forLog="true"></field>
    		<field name="appDate" applyType="TARGET" valueType="FIELD" value="requestDate"/>
    		<field name="requestDate" applyType="SOURCE"/>
    		<field name="authDate" applyType="TARGET" valueType="FIELD" value="authDate"/>
    		<field name="authDate" applyType="SOURCE"/>
    		<field name="type" applyType="TARGET" valueType="FIELD" value="costType"/>
    		<field name="costType" applyType="SOURCE"/>
    		<field name="patentee" applyType="TARGET" valueType="FIELD" value="firstRequest"/>
    		<field name="firstRequest" applyType="SOURCE"/>
    		<field name="status" applyType="TARGET" valueType="FIELD" value="status"/>
    		<field name="status" applyType="SOURCE"/>
    		<field name="amount" applyType="TARGET" valueType="FIELD" value="transfermoney"/>
    		<field name="transfermoney" applyType="SOURCE"/>
    		<field name="linkMan" applyType="TARGET" valueType="FIELD" value="linkMan"/>
    		<field name="linkMan" applyType="SOURCE"/>
    		<field name="linkTel" applyType="TARGET" valueType="FIELD" value="linkTel"/>
    		<field name="linkTel" applyType="SOURCE"/>
    		<field name="address" applyType="TARGET" valueType="FIELD" value="address"/>
    		<field name="address" applyType="SOURCE"/>
    		<field name="batch" applyType="TARGET" valueType="FIELD" value="batch"/>
    		<field name="batch" applyType="SOURCE"/>
    		<field name="bank" applyType="TARGET" valueType="FIELD" value="bank"/>
    		<field name="bank" applyType="SOURCE"/>
    		<field name="bankAccount" applyType="TARGET" valueType="FIELD" value="account"/>
    		<field name="account" applyType="SOURCE"/>
    		<field name="result" applyType="TARGET" valueType="FIELD" value="result"/>
    		<field name="result" applyType="SOURCE"/>
    		<field name="resultTime" applyType="TARGET" valueType="FIELD" value="resultTime"/>
    		<field name="resultTime" applyType="SOURCE"/>
    		<field name="createTime" applyType="TARGET" valueType="FIELD" value="createTime"/>
    		<field name="createTime" applyType="SOURCE"/>
    		<field name="creator" applyType="TARGET" valueType="FIELD" value="creator"/>
    		<field name="creator" applyType="SOURCE"/>
    		<field name="resultor" applyType="TARGET" valueType="FIELD" value="resultor"/>
    		<field name="resultor" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<!-- <condition type="EQUAL" applyType="SOURCE">
    			<field name="costtype" applyType="SOURCE" valueType="FIXED" value="SQ5"></field>
    		</condition> -->
    		<!-- <condition type="ISNOTNULL" applyType="SOURCE">
    			<field name="patentNo" applyType="SOURCE"/>
    		</condition>
    		<condition type="ISNOTNULL" applyType="SOURCE">
    			<field name="costType" applyType="SOURCE"/>
    		</condition> -->
    	</where>
    	<formats>
    		<!-- <format clazz="com.ipph.migratecore.deal.format.PctNoFormater" fieldName="patentNo"/>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="requestCountry">{'QT':'CN','MG':'US','ZG':'CN','RB':'JP','OM':'EP'}</format> -->
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="costType">{'SQ1':'国内发明专利申请','SQ2':'国内发明专利授权','SQ3':'国内工矿企业首个发明专利申请','SQ4':'国内工矿企业首个发明专利授权','SQ5':'（职务）PCT国际专利申请','SQ6':'（职务）国外专利授权'}</format>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="status">{'0':'申请中','1':'审核通过','2':'审核不通过','3':'初审通过','4':'审核过期'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/zpatenthistorySupply_patentNo.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
	 
   <table type="UPDATE" to="z_patent_history" from="patent_upload_model" note="旧系统补录专利更正申请号" skip="false">
    	<fields>
    		<field name="appNumber" applyType="TARGET" valueType="FIELD" value="patent_no" note="专利信息"></field>
    		<field name="patent_no" applyType="SOURCE" note="申请号"></field>
    		<field name="error_app_no" applyType="SOURCE"/>
    	</fields>
    	<where>
            <condition type="EQUAL" applyType="TARGET">
                <field name="appNumber" applyType="TARGET" valueType="FIELD" value="error_app_no"></field>
            </condition>
            <condition type="EQUAL" applyType="SOURCE">
    			<field name="source_type" applyType="SOURCE" valueType="FIXED" value="更正专利号"/>
    		</condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_supply_sub_owner.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_copyright_owner" from="copyright_upload_model" note="软件著作权补助数据迁移-文字-著作权人-补充" skip="false" main="cs_copyright">
    	<fields>
    		<!-- target field list -->
    		<field name="id" applyType="TARGET" valueType="GENCODE"></field>
    		<field name="oid" applyType="TARGET" valueType="FIELD" value="id"/>
    		<field name="ownerName" applyType="TARGET" valueType="FIELD" value="owner_name"/>
    		<!-- source field list -->
    		<field name="id" applyType="SOURCE"/>
    		<field name="owner_name" applyType="SOURCE" forLog="true"/>
    	</fields>
    	<where>
    		<condition type="ISNOTNULL" applyType="SOURCE">
    			<field name="owner_name" applyType="SOURCE"></field>
    		</condition>
    		<condition type="IN" applyType="SOURCE">
    			<field name="type" applyType="SOURCE" valueType="FIXED" value="其他,工程设计、产品设计,工程设计图 产品设计图,工程设计图、产品设计图,戏剧,文字,模型,美术,音乐,摄影"></field>
    		</condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET" value="cs_copyright">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    		<!-- 子表外键 -->
    		<constraint type="FOREIGNKEY" applyType="TARGET">
    			<field name="oid" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    	<splits>
    		<split clazz="com.ipph.migratecore.deal.split.CharacterSpliter" fieldName="copyrightman">[,;\/ :]</split>
    	</splits>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/zpatenthistorySupply_batch.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
	 
   <table type="UPDATE" to="z_patent_history" from="patent_upload_model" note="旧系统补录专利更新批次" skip="false">
    	<fields>
    		<field name="batch" applyType="TARGET" valueType="FIELD" value="batch" note="批次信息"></field>
    		<field name="batch" applyType="SOURCE" note="批次名"></field>
    		<field name="patent_no" applyType="SOURCE"/>
    	</fields>
    	<where>
            <condition type="EQUAL" applyType="TARGET">
                <field name="appNumber" applyType="TARGET" valueType="FIELD" value="patent_no"></field>
            </condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<condition type="EQUAL" applyType="SOURCE">
    			<field name="source_type" applyType="SOURCE" valueType="FIXED" value="更新批次号"/>
    		</condition>
    	</constraints>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_rights_supply_sub_owner.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_rights_copyright_owner" from="copyright_upload_model" note="软件著作权补助数据迁移-影视-著作权人-补充" skip="false" main="cs_rights_copyright">
    	<fields>
    		<!-- target field list -->
    		<field name="id" applyType="TARGET" valueType="GENCODE"></field>
    		<field name="rid" applyType="TARGET" valueType="FIELD" value="id"/>
    		<field name="obligeeName" applyType="TARGET" valueType="FIELD" value="owner_name"/>
    		<!-- source field list -->
    		<field name="id" applyType="SOURCE"/>
    		<field name="owner_name" applyType="SOURCE" forLog="true"/>
    	</fields>
    	<where>
    		<condition type="ISNOTNULL" applyType="SOURCE">
    			<field name="owner_name" applyType="SOURCE"></field>
    		</condition>
    		<condition type="IN" applyType="SOURCE">
    			<field name="type" applyType="SOURCE" valueType="FIXED" value="类似摄制电影方法创作,类似摄制电影方法,录像,电影,录音,类似摄制电影方法创作的作品,录音制品,录像制品"></field>
    		</condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET" value="cs_rights_copyright">
    			<field name="rid" applyType="TARGET"/>
    		</constraint>
    		<!-- 子表外键 -->
    		<constraint type="FOREIGNKEY" applyType="TARGET">
    			<field name="rid" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    	<splits>
    		<split clazz="com.ipph.migratecore.deal.split.CharacterSpliter" fieldName="owner_name">[,;\/ :]</split>
    	</splits>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_supply.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_copyright" from="copyright_upload_model" note="软件著作权补助数据迁移-文字-补充" skip="false">
    	<fields>
    		<!-- target field list -->
    		<field name="id" applyType="TARGET" valueType="FIELD" value="id"></field>
    		<field name="batchNo" applyType="TARGET" valueType="FIELD" value="work_no" note="登记号"></field>
    		<field name="copyrightName" applyType="TARGET" valueType="FIELD" value="work_name"/>
    		<field name="copyrightType" applyType="TARGET" valueType="FIELD" value="type"/>
    		<field name="applicantName" applyType="TARGET" valueType="FIELD" value="applicant_name"/>
    		<field name="RightOwnership" applyType="TARGET" valueType="FIELD" value="right_ownership"/>
    		<field name="RightOwnershipStatus" applyType="TARGET" valueType="FIELD" value="right_ownership_status"/>
    		<field name="applyContacts" applyType="TARGET" valueType="FIELD" value="apply_contacts"/>
    		<field name="applyType" applyType="TARGET" valueType="FIELD" value="apply_type"/>
   			<field name="authorName" applyType="TARGET" valueType="FIELD" value="author_name"/>
   			<field name="finishDate" applyType="TARGET" valueType="FIELD" value="finish_date"/>
   			<field name="firstPublicCity" applyType="TARGET" valueType="FIELD" value="first_public_city"/>
   			<field name="firstPublicDate" applyType="TARGET" valueType="FIELD" value="first_public_date"/>
   			<field name="getRightWay" applyType="TARGET" valueType="FIELD" value="get_right_way"/>
    		<field name="awardDate" applyType="TARGET" valueType="FIELD" value="create_date"/>
    		<field name="registFee" applyType="TARGET" valueType="FIELD" value="regist_fee"/>
    		
    		<field name="supportStatus" applyType="TARGET" valueType="FIXED" value="0"/>
    		<field name="result" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="status" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="odata" applyType="TARGET" valueType="FIXED" value="1"/>
    		
    		<!-- source field list -->
    		<field name="id" applyType="SOURCE"/>
    		<field name="work_no" applyType="SOURCE"/>
    		<field name="work_name" applyType="SOURCE" forLog="true" note="著作权名称"/>
    		<field name="type" applyType="SOURCE"/>
    		<field name="applicant_name" applyType="SOURCE"/>
    		<field name="right_ownership" applyType="SOURCE"/>
    		<field name="right_ownership_status" applyType="SOURCE"/>
    		<field name="apply_contacts" applyType="SOURCE"/>
    		<field name="apply_type" applyType="SOURCE"/>
    		<field name="author_name" applyType="SOURCE"/>
    		<field name="finish_date" applyType="SOURCE"/>
    		<field name="first_public_city" applyType="SOURCE"/>
    		<field name="first_public_date" applyType="SOURCE"/>
    		<field name="get_right_way" applyType="SOURCE"/>
    		<field name="create_date" applyType="SOURCE"/>
    		<field name="regist_fee" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<condition type="IN" applyType="SOURCE">
    			<field name="type" applyType="SOURCE" valueType="FIXED" value="其他,工程设计、产品设计,工程设计图 产品设计图,工程设计图、产品设计图,戏剧,文字,模型,美术,音乐,摄影"></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="type">{'工程设计、产品设计':'图形','工程设计图 产品设计图':'图形','工程设计图、产品设计图':'图形','其他':'其他','戏剧':'戏剧','文字':'文字','模型':'模型','美术':'美术','音乐':'音乐','摄影':'摄影'}</format>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="apply_type">{'由著作人申请':'由著作权人申请','由著作权人申请':'由著作权人申请','由代理人申请':'由代理人申请'}</format>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="get_right_way" defaultValue="其他">{'原始':'原始','继承':'继承','承受':'承受','其他':'其他'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>
