=== yutian1012/migrate-core/src/main/resources/xml/tables.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xsd:element name="tables">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="table" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="table">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="fields" minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- field标签可以出现多次，至少出现1次 -->
							<xsd:element ref="field" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="where">
					<xsd:complexType>
						<xsd:sequence>
							<!-- field标签可以出现多次，至少出现1次 -->
							<xsd:element ref="condition" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="formats">
					<xsd:complexType>
						<xsd:sequence>
							<!-- format标签可以出现多次，至少出现1次 -->
							<xsd:element ref="format" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="constraints" minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- constraint标签可以出现多次，至少出现1次 -->
							<xsd:element ref="constraint" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="splits">
					<xsd:complexType>
						<xsd:sequence>
							<!-- format标签可以出现多次，至少出现1次 -->
							<xsd:element ref="split" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="skip">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="true"/>
						<xsd:enumeration value="false"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
					    <xsd:enumeration value="MIGRATE"/>
					    <xsd:enumeration value="UPDATE"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="to" use="required"></xsd:attribute>
			<xsd:attribute name="from" use="required"></xsd:attribute>
			<xsd:attribute name="note" use="required"></xsd:attribute>
			<xsd:attribute name="main"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="field">
		<xsd:complexType>
			<xsd:attribute name="type">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="VARCHAR"></xsd:enumeration>
						<xsd:enumeration value="DATE"></xsd:enumeration>
						<xsd:enumeration value="NUMERIC"></xsd:enumeration>
						<xsd:enumeration value="BLOB"></xsd:enumeration>
						<xsd:enumeration value="TEXT"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="name" use="required"></xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
			<xsd:attribute name="valueType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="FIXED"></xsd:enumeration>
						<xsd:enumeration value="FIELD"></xsd:enumeration>
						<xsd:enumeration value="GENCODE"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="note"></xsd:attribute>
			<xsd:attribute name="value"></xsd:attribute>
			<xsd:attribute name="forLog">
				<xsd:simpleType>
					<xsd:restriction base="xsd:boolean"></xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="format">
		<xsd:complexType>
			<xsd:attribute name="clazz"></xsd:attribute>
			<!-- <xsd:attribute name="formatParameter"></xsd:attribute> -->
			<xsd:attribute name="fieldName"></xsd:attribute>
			<xsd:attribute name="defaultValue"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="condition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="field" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="LE"></xsd:enumeration>
						<xsd:enumeration value="LT"></xsd:enumeration>
						<xsd:enumeration value="GE"></xsd:enumeration>
						<xsd:enumeration value="GT"></xsd:enumeration>
						<xsd:enumeration value="ISNOTNULL"></xsd:enumeration>
						<xsd:enumeration value="ISNULL"></xsd:enumeration>
						<xsd:enumeration value="LIKE"></xsd:enumeration>
						<xsd:enumeration value="LLIKE"></xsd:enumeration>
						<xsd:enumeration value="RLIKE"></xsd:enumeration>
						<xsd:enumeration value="IN"></xsd:enumeration>
						<xsd:enumeration value="NOTIN"></xsd:enumeration>
						<xsd:enumeration value="EQUAL"></xsd:enumeration>
						<xsd:enumeration value="NEQUAL"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="constraint">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="field" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="PRIMARY"></xsd:enumeration>
						<xsd:enumeration value="FOREIGNKEY"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
			<xsd:attribute name="value"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="split">
		<xsd:complexType>
			<xsd:attribute name="clazz"></xsd:attribute>
			<xsd:attribute name="fieldName"></xsd:attribute>
			<xsd:attribute name="defaultValue"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:attribute name="applyType">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="TARGET"></xsd:enumeration>
				<xsd:enumeration value="SOURCE"></xsd:enumeration>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
</xsd:schema>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_rights_applicantType.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 登记信息申请人类型的更新 -->
   <table type="UPDATE" to="cs_rights_copyright" from="tcopyrightreg" note="登记信息申请人类型的更新-影视" skip="false">
    	<fields>
    		<field name="userType" applyType="TARGET" valueType="FIELD" value="type"></field>
    		<field name="authorname" applyType="SOURCE" note="著作权人" forLog="true"></field>
    		<field name="type" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<!-- <condition type="IN" applyType="SOURCE">
    			<field name="workType" applyType="SOURCE" valueType="FIXED" value="LYZP,LXZP,SY,SZDY,DY"></field>
    		</condition> -->
    		<condition type="EQUAL" applyType="TARGET">
    			<field name="applyName" applyType="TARGET" valueType="FIELD" value="authorname"></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="type" defaultValue="其他">{'FR':'企业','QYFR':'企业','ZRR':'个人','QT':'其他','SYDWFR':'企业','QTZZ':'其他','SHTTFR':'企业','JGFR':'企业'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="rid" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/tables.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tables"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
   xsi:schemaLocation="http://www.migrate.org/schema/tables tables.xsd">
   
   <!-- 专利申请数据的更新 -->
   <table type="UPDATE" to="z_patent" from="tpatentallo" skip="true">
    	<fields>
    		<field to="isApply" from="" field_default="1"></field>
    		<field to="appNumber" from="patentNo">
    			<format>
    				<format_class_name>org.ipph.format.PatentNoFormater</format_class_name>
    			</format>
    		</field>
    		<field to="" from="costtype">
    			<condition type="EQUAL">SQ1</condition>
    		</field>
    	</fields>
    </table>
   
	<!-- <table type="UPDATE" to="tcopyrightallo" from="tcopyrightreg">
		<fields>
			<field to="sourceType" from="tmp">
				<format>
					<format_class_name>org.ipph.format.JsonMethodFormater</format_class_name>
    				<format_class_arg>{'QY':'企业','KYYS':'','GR':'个人','ZCGX':'','SHTT':'','JG':''}</format_class_arg>
				</format>
			</field>
			<field to="" from="workname"></field>
		</fields>
		<where>
			<field to="workname" from="workname">
				<condition type="EQUAL"/>
			</field>
		</where>
	</table> -->
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_sub_owner.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_copyright_owner" from="tcopyrightallo" note="软件著作权补助数据迁移-文字-著作权人" skip="false" main="cs_rights_copyright">
    	<fields>
    		<!-- target field list -->
    		<field name="id" applyType="TARGET" valueType="GENCODE"></field>
    		<field name="oid" applyType="TARGET" valueType="FIELD" value="id"/>
    		<field name="ownerName" applyType="TARGET" valueType="FIELD" value="copyrightman"/>
    		<!-- source field list -->
    		<field name="id" applyType="SOURCE"/>
    		<field name="copyrightman" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<condition type="ISNOTNULL" applyType="SOURCE">
    			<field name="copyrightman" applyType="SOURCE"></field>
    		</condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    	<splits>
    		<split clazz="com.ipph.migratecore.deal.split.CharacterSpliter" fieldName="copyrightman"></split>
    	</splits>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_rights_supply.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_rights_copyright" from="copyright_upload_model" note="软件著作权补助数据迁移-影视-补充" skip="false">
    	<fields>
    		<!-- target field list -->
    		<field name="rid" applyType="TARGET" valueType="FIELD" value="id"></field>
    		<field name="registNo" applyType="TARGET" valueType="FIELD" value="work_no" note="登记号"></field>
    		<field name="copyrightName" applyType="TARGET" valueType="FIELD" value="work_name"/>
    		<field name="copyrightType" applyType="TARGET" valueType="FIELD" value="type"/>
    		<field name="applyName" applyType="TARGET" valueType="FIELD" value="applicant_name"/>
    		<field name="applyContacts" applyType="TARGET" valueType="FIELD" value="apply_contacts"/>
    		<field name="issueDate" applyType="TARGET" valueType="FIELD" value="create_date"/>
    		<field name="creatorName" applyType="TARGET" valueType="FIELD" value="author_name"/>
    		<field name="registFee" applyType="TARGET" valueType="FIELD" value="regist_fee"/>
    		<field name="remark" applyType="TARGET" valueType="FIELD" value="paper_no"/>
    		
    		<field name="supportStatus" applyType="TARGET" valueType="FIXED" value="0"/>
    		<field name="result" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="status" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="odata" applyType="TARGET" valueType="FIXED" value="1"/>
    		
    		<field name="id" applyType="SOURCE"/>
    		<field name="work_no" applyType="SOURCE"/>
    		<field name="work_name" applyType="SOURCE" forLog="true" note="著作权名称"/>
    		<field name="type" applyType="SOURCE"/>
    		<field name="applicant_name" applyType="SOURCE"/>
    		<field name="apply_contacts" applyType="SOURCE"/>
    		<field name="author_name" applyType="SOURCE"/>
    		<field name="create_date" applyType="SOURCE"/>
    		<field name="regist_fee" applyType="SOURCE"/>
    		<field name="paper_no" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<condition type="IN" applyType="SOURCE">
    			<field name="type" applyType="SOURCE" valueType="FIXED" value="类似摄制电影方法创作,类似摄制电影方法,录像,电影,录音,类似摄制电影方法创作的作品,录音制品,录像制品"></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="type" >{'类似摄制电影方法创作':'录像制品','类似摄制电影方法':'录像制品','录像':'录像制品','电影':'录像制品','录音':'录音制品','类似摄制电影方法创作的作品':'录像制品','录音制品':'录音制品','录像制品':'录像制品'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="rid" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/patentApplySupply.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="UPDATE" to="z_patent" from="patent_upload_model" note="专利申请补录数据更新" skip="false">
    	<fields>
    		<field name="isApply" applyType="TARGET" valueType="FIXED" value="1" note="是否已申请"></field>
    		<field name="patentNo" applyType="SOURCE" note="申请号" forLog="true"></field>
    	</fields>
    	<where>
    		<condition type="EQUAL" applyType="SOURCE">
    			<field name="costtype" applyType="SOURCE" valueType="FIXED" value="SQ1"></field>
    		</condition>
    		<condition type="EQUAL" applyType="TARGET">
    			<field name="appNumber" applyType="TARGET" valueType="FIELD" value="patentNo" ></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.PatentNoFormater" fieldName="patentNo"/>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_rights_sub_owner.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_rights_copyright_owner" from="tcopyrightallo" note="软件著作权补助数据迁移-影视-著作权人" skip="false" main="cs_rights_copyright">
    	<fields>
    		<!-- target field list -->
    		<field name="id" applyType="TARGET" valueType="GENCODE"></field>
    		<field name="rid" applyType="TARGET" valueType="FIELD" value="id"/>
    		<field name="obligeeName" applyType="TARGET" valueType="FIELD" value="copyrightman"/>
    		<!-- source field list -->
    		<field name="id" applyType="SOURCE"/>
    		<field name="copyrightman" applyType="SOURCE" forLog="true"/>
    	</fields>
    	<where>
    		<condition type="ISNOTNULL" applyType="SOURCE">
    			<field name="copyrightman" applyType="SOURCE"></field>
    		</condition>
    		<condition type="IN" applyType="SOURCE">
    			<field name="workType" applyType="SOURCE" valueType="FIXED" value="LYZP,LXZP,SY,SZDY,DY"></field>
    		</condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET" value="cs_rights_copyright">
    			<field name="rid" applyType="TARGET"/>
    		</constraint>
    		<!-- 子表外键 -->
    		<constraint type="FOREIGNKEY" applyType="TARGET">
    			<field name="rid" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    	<splits>
    		<split clazz="com.ipph.migratecore.deal.split.CharacterSpliter" fieldName="copyrightman">[,;\/ :]</split>
    	</splits>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/patentAuthSupply.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="UPDATE" to="z_patent" from="patent_upload_model" note="专利授权补录数据更新" skip="false">
    	<fields>
    		<field name="iscity" applyType="TARGET" valueType="FIXED" value="1" note="是否已授权"></field>
    		<field name="patent_no" applyType="SOURCE" note="申请号" forLog="true"></field>
    		<field name="cost_type" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<condition type="EQUAL" applyType="SOURCE">
    			<field name="cost_type" applyType="SOURCE" valueType="FIXED" value="SQ2"></field>
    		</condition>
    		<condition type="EQUAL" applyType="TARGET">
    			<field name="appNumber" applyType="TARGET" valueType="FIELD" value="patent_no" ></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.PatentNoFormater" fieldName="patent_no"/>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/test/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tables"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
   xsi:schemaLocation="http://www.migrate.org/schema/tables tables.xsd">
   
   <!-- 专利申请数据的更新 -->
   <table type="UPDATE" to="z_patent" from="tpatentallo" skip="true">
    	<fields>
    		<field name="isApply" applyType="TARGET" valueType="FIXED" value="1"></field>
    		<field name="patentNo" applyType="SOURCE"></field>
    	</fields>
    	<where>
    		<condition type="EQUAL" applyType="SOURCE">
    			<field name="costtype" applyType="SOURCE" valueType="FIXED" value="SQ1"></field>
    		</condition>
    		<condition type="EQUAL" applyType="TARGET">
    			<field name="appNumber" applyType="TARGET" valueType="FIELD" value="patentNo" ></field>
    		</condition>
    	</where>
    	<!-- <formats>
    		<format clazz="" ></format>
    	</formats> -->
    </table>
</tables>
