=== yutian1012/migrate-core/src/main/resources/xml/tables.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xsd:element name="tables">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="table" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="table">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="fields" minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- field标签可以出现多次，至少出现1次 -->
							<xsd:element ref="field" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="where">
					<xsd:complexType>
						<xsd:sequence>
							<!-- field标签可以出现多次，至少出现1次 -->
							<xsd:element ref="condition" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="formats">
					<xsd:complexType>
						<xsd:sequence>
							<!-- format标签可以出现多次，至少出现1次 -->
							<xsd:element ref="format" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="constraints" minOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- constraint标签可以出现多次，至少出现1次 -->
							<xsd:element ref="constraint" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="splits">
					<xsd:complexType>
						<xsd:sequence>
							<!-- format标签可以出现多次，至少出现1次 -->
							<xsd:element ref="split" minOccurs="1"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="skip">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="true"/>
						<xsd:enumeration value="false"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
					    <xsd:enumeration value="MIGRATE"/>
					    <xsd:enumeration value="UPDATE"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="to" use="required"></xsd:attribute>
			<xsd:attribute name="from" use="required"></xsd:attribute>
			<xsd:attribute name="note" use="required"></xsd:attribute>
			<xsd:attribute name="main"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="field">
		<xsd:complexType>
			<xsd:attribute name="type">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="VARCHAR"></xsd:enumeration>
						<xsd:enumeration value="DATE"></xsd:enumeration>
						<xsd:enumeration value="NUMERIC"></xsd:enumeration>
						<xsd:enumeration value="BLOB"></xsd:enumeration>
						<xsd:enumeration value="TEXT"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="name" use="required"></xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
			<xsd:attribute name="valueType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="FIXED"></xsd:enumeration>
						<xsd:enumeration value="FIELD"></xsd:enumeration>
						<xsd:enumeration value="GENCODE"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="note"></xsd:attribute>
			<xsd:attribute name="value"></xsd:attribute>
			<xsd:attribute name="forLog">
				<xsd:simpleType>
					<xsd:restriction base="xsd:boolean"></xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="format">
		<xsd:complexType>
			<xsd:attribute name="clazz"></xsd:attribute>
			<!-- <xsd:attribute name="formatParameter"></xsd:attribute> -->
			<xsd:attribute name="fieldName"></xsd:attribute>
			<xsd:attribute name="defaultValue"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="condition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="field" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="LE"></xsd:enumeration>
						<xsd:enumeration value="LT"></xsd:enumeration>
						<xsd:enumeration value="GE"></xsd:enumeration>
						<xsd:enumeration value="GT"></xsd:enumeration>
						<xsd:enumeration value="ISNOTNULL"></xsd:enumeration>
						<xsd:enumeration value="ISNULL"></xsd:enumeration>
						<xsd:enumeration value="LIKE"></xsd:enumeration>
						<xsd:enumeration value="LLIKE"></xsd:enumeration>
						<xsd:enumeration value="RLIKE"></xsd:enumeration>
						<xsd:enumeration value="IN"></xsd:enumeration>
						<xsd:enumeration value="NOTIN"></xsd:enumeration>
						<xsd:enumeration value="EQUAL"></xsd:enumeration>
						<xsd:enumeration value="NEQUAL"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="constraint">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="field" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="PRIMARY"></xsd:enumeration>
						<xsd:enumeration value="FOREIGNKEY"></xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute ref="applyType" use="required"></xsd:attribute>
			<xsd:attribute name="value"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="split">
		<xsd:complexType>
			<xsd:attribute name="clazz"></xsd:attribute>
			<xsd:attribute name="fieldName"></xsd:attribute>
			<xsd:attribute name="defaultValue"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:attribute name="applyType">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="TARGET"></xsd:enumeration>
				<xsd:enumeration value="SOURCE"></xsd:enumeration>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
</xsd:schema>

=== yutian1012/migrate-core/src/main/resources/xml/zpatenthistorySupply.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利旧系统数据处理 -->
   <table type="MIGRATE" to="z_patent_history" from="patent_upload_model" note="专利旧系统数据补录" skip="false">
    	<fields>
    		<field name="id" applyType="TARGET" valueType="FIELD" value="id" note="主键字段"></field>
    		<field name="id" applyType="SOURCE"/>
    		<field name="patentName" applyType="TARGET" valueType="FIELD" value="patent_name"/>
    		<field name="patent_name" applyType="SOURCE"/>
    		<field name="appNumber" applyType="TARGET" valueType="FIELD" value="patent_no"/>
    		<field name="patent_no" applyType="SOURCE" note="申请号" forLog="true"></field>
    		<field name="appDate" applyType="TARGET" valueType="FIELD" value="request_date"/>
    		<field name="request_date" applyType="SOURCE"/>
    		<field name="authDate" applyType="TARGET" valueType="FIELD" value="auth_date"/>
    		<field name="auth_date" applyType="SOURCE"/>
    		<field name="type" applyType="TARGET" valueType="FIELD" value="cost_type"/>
    		<field name="cost_type" applyType="SOURCE"/>
    		<field name="patentee" applyType="TARGET" valueType="FIELD" value="first_request"/>
    		<field name="first_request" applyType="SOURCE"/>
    		<field name="status" applyType="TARGET" valueType="FIELD" value="status"/>
    		<field name="status" applyType="SOURCE"/>
    		<field name="amount" applyType="TARGET" valueType="FIELD" value="transfer_money"/>
    		<field name="transfer_money" applyType="SOURCE"/>
    		<field name="linkMan" applyType="TARGET" valueType="FIELD" value="link_man"/>
    		<field name="link_man" applyType="SOURCE"/>
    		<field name="linkTel" applyType="TARGET" valueType="FIELD" value="link_tel"/>
    		<field name="link_tel" applyType="SOURCE"/>
    		<field name="address" applyType="TARGET" valueType="FIELD" value="address"/>
    		<field name="address" applyType="SOURCE"/>
    		<field name="batch" applyType="TARGET" valueType="FIELD" value="batch"/>
    		<field name="batch" applyType="SOURCE"/>
    		<field name="bank" applyType="TARGET" valueType="FIELD" value="bank"/>
    		<field name="bank" applyType="SOURCE"/>
    		<field name="bankAccount" applyType="TARGET" valueType="FIELD" value="bank_account"/>
    		<field name="bank_account" applyType="SOURCE"/>
    		<field name="result" applyType="TARGET" valueType="FIELD" value="result"/>
    		<field name="result" applyType="SOURCE"/>
    		<field name="resultTime" applyType="TARGET" valueType="FIELD" value="result_time"/>
    		<field name="result_time" applyType="SOURCE"/>
    		<field name="createTime" applyType="TARGET" valueType="FIELD" value="create_time"/>
    		<field name="create_time" applyType="SOURCE"/>
    		<field name="creator" applyType="TARGET" valueType="FIELD" value="creator"/>
    		<field name="creator" applyType="SOURCE"/>
    		<field name="resultor" applyType="TARGET" valueType="FIELD" value="resultor"/>
    		<field name="resultor" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<condition type="EQUAL" applyType="SOURCE">
    			<field name="source_type" applyType="SOURCE" valueType="FIXED" value="插入"/>
    		</condition>
    		<!--<condition type="ISNOTNULL" applyType="SOURCE">
    			<field name="costType" applyType="SOURCE"/>
    		</condition>-->
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="cost_type">{'SQ1':'国内发明专利申请','SQ2':'国内发明专利授权','SQ3':'国内工矿企业首个发明专利申请','SQ4':'国内工矿企业首个发明专利授权','SQ5':'（职务）PCT国际专利申请','SQ6':'（职务）国外专利授权'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/test/resources/migrateupdate.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tables"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
   xsi:schemaLocation="http://www.migrate.org/schema/tables tables.xsd">
	<!-- 测试数据更新 -->
    <table type="UPDATE" to="migratedest" from="migratesource">
    	<fields>
    		<!-- 目标表要更新的字段 -->
    		<field name="useremail" applyType="TARGET" valueType="FIELD" value="email"/>
    		<!-- 源表要查询获取的字段数据 -->
    		<field name="name" applyType="SOURCE"/>
    		<field name="email" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<!-- 目标表更新数据的条件，migratesource表使用name字段，migratedest使用username字段进行关联更新  -->
    		<condition type="EQUAL" applyType="TARGET">
    			<field name="username" applyType="TARGET" valueType="FIELD" value="name"/>
    		</condition>
    		<!-- 源表获取待更新的数据集条件，这里设置id值<=3 -->
    		<condition type="LE" applyType="SOURCE">
    			<field name="id" applyType="SOURCE" valueType="FIXED" value="3" />
    		</condition>
    	</where>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/copyright_rights.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_rights_copyright" from="tcopyrightallo" note="软件著作权补助数据迁移-影视" skip="false">
    	<fields>
    		<!-- target field list -->
    		<field name="rid" applyType="TARGET" valueType="FIELD" value="id"></field>
    		<field name="registNo" applyType="TARGET" valueType="FIELD" value="workno" note="登记号"></field>
    		<field name="copyrightName" applyType="TARGET" valueType="FIELD" value="workname"/>
    		<field name="copyrightType" applyType="TARGET" valueType="FIELD" value="workType"/>
    		<field name="issueDate" applyType="TARGET" valueType="FIELD" value="releasedate"/>
    		<field name="registFee" applyType="TARGET" valueType="FIELD" value="regcost"/>
    		<field name="applyName" applyType="TARGET" valueType="FIELD" value="name"/>
    		<field name="applyAddress" applyType="TARGET" valueType="FIELD" value="address"/>
    		<field name="applyPostalcode" applyType="TARGET" valueType="FIELD" value="zip"/>
    		<field name="applyContacts" applyType="TARGET" valueType="FIELD" value="linkman"/>
    		<field name="applyPhone" applyType="TARGET" valueType="FIELD" value="linkphone"/>
    		<field name="applyEmail" applyType="TARGET" valueType="FIELD" value="email"/>
    		<field name="applyTel" applyType="TARGET" valueType="FIELD" value="mobile"/>
    		<field name="applyFax" applyType="TARGET" valueType="FIELD" value="fax"/>
    		<field name="createDate" applyType="TARGET" valueType="FIELD" value="createTime"/>
    		<field name="county" applyType="TARGET" valueType="FIELD" value="area"/>
    		<field name="supportStatus" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="result" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="status" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="odata" applyType="TARGET" valueType="FIXED" value="1"/>
    		
    		<!-- source field list -->
    		<field name="id" applyType="SOURCE"/>
    		<field name="workno" applyType="SOURCE"/>
    		<field name="workname" applyType="SOURCE" forLog="true" note="著作权名称"/>
    		<field name="workType" applyType="SOURCE"/>
    		<field name="sourceType" applyType="SOURCE"/>
    		<field name="worker" applyType="SOURCE"/>
    		<field name="copyrightman" applyType="SOURCE"/>
    		<field name="releasedate" applyType="SOURCE"/>
    		<field name="regcost" applyType="SOURCE"/>
    		<field name="name" applyType="SOURCE"/>
    		<field name="address" applyType="SOURCE"/>
    		<field name="zip" applyType="SOURCE"/>
    		<field name="linkman" applyType="SOURCE"/>
    		<field name="linkphone" applyType="SOURCE"/>
    		<field name="email" applyType="SOURCE"/>
    		<field name="mobile" applyType="SOURCE"/>
    		<field name="fax" applyType="SOURCE"/>
    		<field name="createTime" applyType="SOURCE"/>
    		<field name="area" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<condition type="IN" applyType="SOURCE">
    			<field name="workType" applyType="SOURCE" valueType="FIXED" value="LYZP,LXZP,SY,SZDY,DY"></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="workType" defaultValue="录像制品">{'LXZP':'录像制品','LYZP':'录音制品','SY':'录像制品','SZDY':'录像制品','DY':'录像制品'}</format>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="area">{'YLQ':'岳麓区','GXQ':'高新区','HRQ':'芙蓉区','YHQ':'雨花区','JKQ':'经开区','KFQ':'开福区','TXQ':'天心区','CSX':'长沙县','LXX':'宁乡县','LYX':'浏阳市','WCQ':'望城区'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="rid" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/tcopyrightallo_tcopyrightreg_dest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 登记信息申请人类型的更新 -->
   <table type="UPDATE" to="tcopyrightreg_dest" from="tcopyrightallo" note="历史数据中著作权资助与登记不符的记录" skip="false">
    	<fields>
    		<field name="remark" applyType="TARGET" valueType="FIXED" value="1"></field>
    		<field name="copyrightman" applyType="SOURCE" note="著作权人" forLog="true"></field>
    	</fields>
    	<where>
    		<!-- <condition type="IN" applyType="SOURCE">
    			<field name="workType" applyType="SOURCE" valueType="FIXED" value="LYZP,LXZP,SY,SZDY,DY"></field>
    		</condition> -->
    		<condition type="EQUAL" applyType="TARGET">
    			<field name="authorname" applyType="TARGET" valueType="FIELD" value="copyrightman"></field>
    		</condition>
    	</where>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/main/resources/xml/patentPctAuthSupply.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="wf_patent_support_foreign" from="patent_upload_model" note="专利PCT补录授权数据迁移" skip="false">
    	<fields>
    		<field name="id" applyType="TARGET" valueType="FIELD" value="id" note="主键字段"></field>
    		<field name="id" applyType="SOURCE"/>
    		<field name="patentName" applyType="TARGET" valueType="FIELD" value="patent_name"/>
    		<field name="patent_name" applyType="SOURCE"/>
    		<field name="applyNo" applyType="TARGET" valueType="FIELD" value="patent_no"/>
    		<field name="patent_no" applyType="SOURCE" note="申请号" forLog="true"></field>
    		<field name="applyDate" applyType="TARGET" valueType="FIELD" value="request_date"/>
    		<field name="request_date" applyType="SOURCE"/>
    		<field name="authDate" applyType="TARGET" valueType="FIELD" value="auth_date"/>
    		<field name="auth_date" applyType="SOURCE"/>
    		<field name="country" applyType="TARGET" valueType="FIELD" value="request_country"/>
    		<field name="request_country" applyType="SOURCE"/>
    		<field name="applyer" applyType="TARGET" valueType="FIELD" value="first_request"/>
    		<field name="first_request" applyType="SOURCE"/>
    		<field name="money" applyType="TARGET" valueType="FIELD" value="transfer_money"/>
    		<field name="transfer_money" applyType="SOURCE"/>
    		<field name="statusType" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="type" applyType="TARGET" valueType="FIXED" value="1"/>
    	</fields>
    	<where>
    		<condition type="EQUAL" applyType="SOURCE">
    			<field name="cost_type" applyType="SOURCE" valueType="FIXED" value="SQ6"></field>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.PctNoFormater" fieldName="patent_no"/>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="request_country">{'QT':'CN','MG':'US','ZG':'CN','RB':'JP','OM':'EP'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>

=== yutian1012/migrate-core/src/test/resources/copyright_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="http://www.migrate.org/schema/tableschema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:schemaLocation="http://www.migrate.org/schema/tableschema tables.xsd" >
    <!-- 专利申请数据的更新 -->
   <table type="MIGRATE" to="cs_copyright_dest" from="tcopyrightallo" note="软件著作权补助数据迁移" skip="false">
    	<fields>
    		<!-- target field list -->
    		<field name="id" applyType="TARGET" valueType="FIELD" value="id"></field>
    		<field name="batchNo" applyType="TARGET" valueType="FIELD" value="workno" note="登记号"></field>
    		<field name="copyrightName" applyType="TARGET" valueType="FIELD" value="workname"/>
    		<field name="copyrightType" applyType="TARGET" valueType="FIELD" value="workType"/>
    		<field name="userType" applyType="TARGET" valueType="FIELD" value="sourceType"/>
    		<field name="authorName" applyType="TARGET" valueType="FIELD" value="worker"/>
    		<field name="ownerName" applyType="TARGET" valueType="FIELD" value="copyrightman"/>
    		<field name="awardDate" applyType="TARGET" valueType="FIELD" value="releasedate"/>
    		<field name="registFee" applyType="TARGET" valueType="FIELD" value="regcost"/>
    		<field name="applicantName" applyType="TARGET" valueType="FIELD" value="name"/>
    		<field name="applicantAddress" applyType="TARGET" valueType="FIELD" value="address"/>
    		<field name="applicantPostcode" applyType="TARGET" valueType="FIELD" value="zip"/>
    		<field name="applyContacts" applyType="TARGET" valueType="FIELD" value="linkman"/>
    		<field name="applicantTel" applyType="TARGET" valueType="FIELD" value="linkphone"/>
    		<field name="applicantEmail" applyType="TARGET" valueType="FIELD" value="email"/>
    		<field name="applyContactsPhone" applyType="TARGET" valueType="FIELD" value="mobile"/>
    		<field name="applicantFax" applyType="TARGET" valueType="FIELD" value="fax"/>
    		<field name="createDate" applyType="TARGET" valueType="FIELD" value="createTime"/>
    		<field name="county" applyType="TARGET" valueType="FIELD" value="area"/>
    		<field name="supportStatus" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="result" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="status" applyType="TARGET" valueType="FIXED" value="1"/>
    		<field name="odata" applyType="TARGET" valueType="FIXED" value="1"/>
    		<!-- source field list -->
    		<field name="id" applyType="SOURCE"/>
    		<field name="workno" applyType="SOURCE"/>
    		<field name="workname" applyType="SOURCE" forLog="true" note="著作权名称"/>
    		<field name="workType" applyType="SOURCE"/>
    		<field name="sourceType" applyType="SOURCE"/>
    		<field name="worker" applyType="SOURCE"/>
    		<field name="copyrightman" applyType="SOURCE"/>
    		<field name="releasedate" applyType="SOURCE"/>
    		<field name="regcost" applyType="SOURCE"/>
    		<field name="name" applyType="SOURCE"/>
    		<field name="address" applyType="SOURCE"/>
    		<field name="zip" applyType="SOURCE"/>
    		<field name="linkman" applyType="SOURCE"/>
    		<field name="linkphone" applyType="SOURCE"/>
    		<field name="email" applyType="SOURCE"/>
    		<field name="mobile" applyType="SOURCE"/>
    		<field name="fax" applyType="SOURCE"/>
    		<field name="createTime" applyType="SOURCE"/>
    		<field name="area" applyType="SOURCE"/>
    	</fields>
    	<where>
    		<condition type="NOTIN" applyType="SOURCE">
    			<field name="workType" applyType="SOURCE" valueType="FIXED" value="LYZP,LXZP,SY,SZDY,DY"></field>
    		</condition>
    		<condition type="LE" applyType="SOURCE">
    			<field name="id" applyType="SOURCE" valueType="FIXED" value="1000"/>
    		</condition>
    	</where>
    	<formats>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="workType">{'WZ':'文字','KS':'口述','YY':'音乐','XJ':'戏剧','QY':'曲艺','WD':'舞蹈','ZJ':'杂技艺术','MS':'美术','JZ':'建筑','SJT':'图形','MX':'模型','QT':'其他','RJ':'其他','DT':'图形'}</format>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="sourceType">{'QY':'企业','KYYS':'其他','GR':'个人','ZCGX':'高校','SHTT':'其他','JG':'其他'}</format>
    		<format clazz="com.ipph.migratecore.deal.format.JsonMethodFormater" fieldName="area">{'YLQ':'岳麓区','GXQ':'高新区','HRQ':'芙蓉区','YHQ':'雨花区','JKQ':'经开区','KFQ':'开福区','TXQ':'天心区','CSX':'长沙县','LXX':'宁乡县','LYX':'浏阳市','WCQ':'望城区'}</format>
    	</formats>
    	<constraints>
    		<constraint type="PRIMARY" applyType="SOURCE">
    			<field name="id" applyType="SOURCE"/>
    		</constraint>
    		<constraint type="PRIMARY" applyType="TARGET">
    			<field name="id" applyType="TARGET"/>
    		</constraint>
    	</constraints>
    </table>
</tables>
